
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    entrypoint: "ollama serve"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia

  app:
    build:
      context: .
    container_name: sentiment-app
    ports:
      - "8000:8000"
      - "7860:7860"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - API_URL=http://sentiment-app:8000/classify
    volumes:
      - .:/app
    command: bash start.sh
    restart: unless-stopped

volumes:
  ollama_models:
